#ifndef ANT_DESKTOP_CONTROL_H
#define ANT_DESKTOP_CONTROL_H

#include <stddef.h>
#include <stdint.h>

#define ANT_DESKTOP_CONTROL_MAGIC 0x414E5444u
#define ANT_DESKTOP_CONTROL_TEXT_CAPACITY 65536u

typedef enum ant_desktop_control_type {
  ANT_DESKTOP_CONTROL_MOUSE_MOVE = 1,
  ANT_DESKTOP_CONTROL_MOUSE_LEAVE,
  ANT_DESKTOP_CONTROL_MOUSE_DOWN,
  ANT_DESKTOP_CONTROL_MOUSE_UP,
  ANT_DESKTOP_CONTROL_SCROLL,
  ANT_DESKTOP_CONTROL_KEY_DOWN,
  ANT_DESKTOP_CONTROL_KEY_UP,
  ANT_DESKTOP_CONTROL_FOCUS,
  ANT_DESKTOP_CONTROL_RESIZE,
  ANT_DESKTOP_CONTROL_IME_SET,
  ANT_DESKTOP_CONTROL_IME_COMMIT,
  ANT_DESKTOP_CONTROL_IME_FINISH,
  ANT_DESKTOP_CONTROL_GESTURE_MAGNIFY,
  ANT_DESKTOP_CONTROL_GESTURE_ROTATE,
  ANT_DESKTOP_CONTROL_GESTURE_SWIPE,
  ANT_DESKTOP_CONTROL_IPC_RESOLVE,
  ANT_DESKTOP_CONTROL_IPC_REJECT,
  ANT_DESKTOP_CONTROL_IPC_EVENT,
  ANT_DESKTOP_CONTROL_OPEN_DEVTOOLS,
  ANT_DESKTOP_CONTROL_CLOSE_DEVTOOLS,
  ANT_DESKTOP_CONTROL_TOGGLE_DEVTOOLS,
  ANT_DESKTOP_CONTROL_INSPECT_ELEMENT,
  ANT_DESKTOP_CONTROL_RELOAD,
} ant_desktop_control_type_t;

typedef enum ant_desktop_modifier {
  ANT_DESKTOP_MODIFIER_SHIFT = 1u << 0,
  ANT_DESKTOP_MODIFIER_CONTROL = 1u << 1,
  ANT_DESKTOP_MODIFIER_ALT = 1u << 2,
  ANT_DESKTOP_MODIFIER_COMMAND = 1u << 3,
  ANT_DESKTOP_MODIFIER_CAPS_LOCK = 1u << 4,
  ANT_DESKTOP_MODIFIER_KEYPAD = 1u << 5,
  ANT_DESKTOP_MODIFIER_LEFT_BUTTON = 1u << 6,
  ANT_DESKTOP_MODIFIER_RIGHT_BUTTON = 1u << 7,
  ANT_DESKTOP_MODIFIER_MIDDLE_BUTTON = 1u << 8,
} ant_desktop_modifier_t;

typedef struct ant_desktop_control_message {
  uint32_t magic;
  uint32_t size;
  uint32_t type;
  uint32_t modifiers;
  uint64_t sequence;
  double x;
  double y;
  double delta_x;
  double delta_y;
  uint32_t key_code;
  uint32_t button;
  uint32_t click_count;
  uint32_t selection_start;
  uint32_t selection_length;
  uint32_t text_length;
  char text[ANT_DESKTOP_CONTROL_TEXT_CAPACITY];
} ant_desktop_control_message_t;

#define ANT_DESKTOP_CONTROL_HEADER_SIZE ((uint32_t)offsetof(ant_desktop_control_message_t, text))

#endif
